// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjFCEHJVu-eGTAuKzFJowJebUi035jAsY',
    appId: '1:1097476358152:web:1b2837d1be8ddf865f51bd',
    messagingSenderId: '1097476358152',
    projectId: 'appcomu-8fbc4',
    authDomain: 'appcomu-8fbc4.firebaseapp.com',
    storageBucket: 'appcomu-8fbc4.firebasestorage.app',
    measurementId: 'G-02Y2V7X9N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjQRxHcBfwPqykcMrkPHRM0UleW_jV6ys',
    appId: '1:1097476358152:android:379bf2f25fb62aac5f51bd',
    messagingSenderId: '1097476358152',
    projectId: 'appcomu-8fbc4',
    storageBucket: 'appcomu-8fbc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZTRujYQvMc841lVTD7wL7Ax6KB9Vpdos',
    appId: '1:1097476358152:ios:5fc7ce153c5d94b85f51bd',
    messagingSenderId: '1097476358152',
    projectId: 'appcomu-8fbc4',
    storageBucket: 'appcomu-8fbc4.firebasestorage.app',
    iosBundleId: 'com.example.appComu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZTRujYQvMc841lVTD7wL7Ax6KB9Vpdos',
    appId: '1:1097476358152:ios:5fc7ce153c5d94b85f51bd',
    messagingSenderId: '1097476358152',
    projectId: 'appcomu-8fbc4',
    storageBucket: 'appcomu-8fbc4.firebasestorage.app',
    iosBundleId: 'com.example.appComu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjFCEHJVu-eGTAuKzFJowJebUi035jAsY',
    appId: '1:1097476358152:web:8c7294282bf563825f51bd',
    messagingSenderId: '1097476358152',
    projectId: 'appcomu-8fbc4',
    authDomain: 'appcomu-8fbc4.firebaseapp.com',
    storageBucket: 'appcomu-8fbc4.firebasestorage.app',
    measurementId: 'G-GSRE3HVEK6',
  );
}
